Repository SmartBrush/Backend, pull requests merged in 2025-08, with the labels that each got.

#52 ✨ [FEAT] 진단 결과 점수 계산
  src/main/java/com/smartbrush/smartbrush_backend/controller/DiagnosisController.java
Labels: ✨ Feature

#75 🐛 [FIX] 이미지 컨트롤러 수정
  src/main/java/com/smartbrush/smartbrush_backend/controller/CaptureController.java
  src/main/java/com/smartbrush/smartbrush_backend/controller/ImageUploadController.java
Labels: 🐛 BugFix, 📬 API

#76 🐛 [FIX] S3 수정
  src/main/java/com/smartbrush/smartbrush_backend/config/SwaggerConfig.java
  src/main/java/com/smartbrush/smartbrush_backend/controller/CaptureController.java
  src/main/java/com/smartbrush/smartbrush_backend/controller/ImageUploadController.java
Labels: 🐛 BugFix

#83 ✨ [FEAT] 습관 챌린지
  src/main/java/com/smartbrush/smartbrush_backend/config/SecurityConfig.java
  src/main/java/com/smartbrush/smartbrush_backend/controller/DailyHabitController.java
  src/main/java/com/smartbrush/smartbrush_backend/dto/habit/DailyHabitItemDTO.java
  src/main/java/com/smartbrush/smartbrush_backend/dto/habit/DailyHabitResponseDTO.java
  src/main/java/com/smartbrush/smartbrush_backend/entity/DailyHabitEntity.java
  src/main/java/com/smartbrush/smartbrush_backend/entity/HabitCategory.java
  src/main/java/com/smartbrush/smartbrush_backend/repository/DailyHabitRepository.java
  src/main/java/com/smartbrush/smartbrush_backend/service/DailyHabitService.java
  src/main/java/com/smartbrush/smartbrush_backend/service/DailyHabitServiceImpl.java
  src/main/java/com/smartbrush/smartbrush_backend/support/HabitCatalog.java
Labels: ✨ Feature

#90 ✨ [FEAT] 두피 MBTI + 제품추천
  src/main/java/com/smartbrush/smartbrush_backend/controller/DiagnosisController.java
  src/main/java/com/smartbrush/smartbrush_backend/controller/ProductController.java
  src/main/java/com/smartbrush/smartbrush_backend/dto/MBTI/ScalpMbtiSummaryDTO.java
  src/main/java/com/smartbrush/smartbrush_backend/repository/DiagnosisRepository.java
  src/main/java/com/smartbrush/smartbrush_backend/service/ProductRecommendationServiceImpl.java
  src/main/java/com/smartbrush/smartbrush_backend/service/ScalpMbtiServiceImpl.java
Labels: ✨ Feature

#92 고민공유페이지 좋아요 및 댓글 카운트 추가
  src/main/java/com/smartbrush/smartbrush_backend/controller/CommunityController.java
  src/main/java/com/smartbrush/smartbrush_backend/controller/PostController.java
  src/main/java/com/smartbrush/smartbrush_backend/dto/community/CommunityResponseDTO.java
  src/main/java/com/smartbrush/smartbrush_backend/dto/post/PostRequestDto.java
  src/main/java/com/smartbrush/smartbrush_backend/dto/post/PostResponseDto.java
  src/main/java/com/smartbrush/smartbrush_backend/entity/AuthEntity.java
  src/main/java/com/smartbrush/smartbrush_backend/entity/CommunityLikeEntity.java
  src/main/java/com/smartbrush/smartbrush_backend/entity/Post.java
  src/main/java/com/smartbrush/smartbrush_backend/repository/CommentRepository.java
  src/main/java/com/smartbrush/smartbrush_backend/repository/CommunityLikeRepository.java
  src/main/java/com/smartbrush/smartbrush_backend/repository/PostRepository.java
  src/main/java/com/smartbrush/smartbrush_backend/service/CommunityLikeService.java
  src/main/java/com/smartbrush/smartbrush_backend/service/CommunityService.java
  src/main/java/com/smartbrush/smartbrush_backend/service/CommunityServiceImpl.java
  src/main/java/com/smartbrush/smartbrush_backend/service/PostService.java
Labels: ✨ Feature

#93 ✨ [FEAT] AI API 수정
  src/main/java/com/smartbrush/smartbrush_backend/controller/DiagnosisController.java
Labels: ✨ Feature

#100 ✨ [FEAT] 이미지여러개
  src/main/java/com/smartbrush/smartbrush_backend/controller/DiagnosisController.java
Labels: ✨ Feature

#108 ✨ [FEAT] 질문 답변 유무 생성
  src/main/java/com/smartbrush/smartbrush_backend/dto/question/UserProfileInfoResponseDTO.java
  src/main/java/com/smartbrush/smartbrush_backend/entity/UserProfileInfo.java
  src/main/java/com/smartbrush/smartbrush_backend/service/ProfileInfoServiceImpl.java
Labels: ✨ Feature

#110 ✨ [FEAT] AI에 이미지 자동 업로드
  src/main/java/com/smartbrush/smartbrush_backend/controller/DiagnosisController.java
  src/main/java/com/smartbrush/smartbrush_backend/controller/ImageUploadController.java
  src/main/java/com/smartbrush/smartbrush_backend/storage/S3Uploader.java
Labels: ✨ Feature
